name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Check 1
      run: cd.. && ls
    - name: Check 2
      run: ls
    - name: Check 3
      run: cd.. && cd..
    - name: Check path
      run: pwd
    - name: Install dependencies
      run:  flutter pub get
    - name: Run tests
      run:  flutter pub run test
